apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: elliottwes6-poi-map-app-dev
  annotations:
    argocd/app-name: elliottwes6-poi-map-app-dev
    backstage.io/kubernetes-id: elliottwes6-poi-map-app
    backstage.io/kubernetes-namespace: elliottwes6
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-deploy/elliottwes6-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/dev-pipelines/ns/elliottwes6/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/k8s/ns/elliottwes6/deployments/elliottwes6-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.a1jxqhzp.eastus2.aroapp.io/#https://github.com/rhdh-deploy/elliottwes6-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://elliottwes6-poi-map-app-elliottwes6.apps.a1jxqhzp.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/elliottwes6"
  system: workshop-system-elliottwes6
  consumesApis:
    - gateway-api-elliottwes6
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-elliottwes6
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/elliottwes6"
